### ISSUE TITLE
Use "crypto-js" dep instead of "crypto"

### ISSUE THREAD

**Issue by adcpm** [adcpm/steemauth#6]
The dependancy we are using "crypto" is not well maintained and cause issue with Meteor. "crypto-js" seem to be a good fit for solve this issues.

**Comment by nil1511** [comment]
current crypto module is not being used. we are using nodejs's crypto api. 
try removing it from package.json and node_modules.

**Comment by adcpm** [comment]
After removing crypto or using last version of steem with steemauth 0.17 it will not show crypto error but still showing this error: Error: 3030008 tx_missing_posting_auth: missing required posting authority while voting

**Comment by nil1511** [comment]
Closed in b961e36
